version: "3"

services:
  nuxt:
    build: .
    container_name: vena_app
    restart: always
    ports:
      - "3050:3050"
    command:
      "npm run start"

  nginx:
    image: nginx:1.13
    container_name: vena-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
